[tool.poetry]
name = "my_page"
version = "0.0.0"
description = ""
authors = ["hrostmy <s.hromosiak@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
